language: python
python:
  - "3.7"

services:
  - docker

before_install:
- cp .ignored.file.copy ignored.file

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test"

